import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

import './globals.css'
import StyledComponentsRegistry from '@/lib/register'
import { Providers } from './proviers'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '600']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <StyledComponentsRegistry>
          <Providers>{children}</Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
